### ISSUE TITLE
Make OAuth flows configurable in Cognito module

### ISSUE THREAD

**Issue by barmic12** [TheMomentumAI/healthstack#18]
First and foremost, great job on enabling SMART on FHIR configuration in Healthlake. It looks like a huge time-saver!

Here is the first improvement suggestion - currently, there is no way to configure which OAuth flows should be allowed. It is hardcoded in this line:

https://github.com/TheMomentumAI/healthstack/blob/main/healthlake/cognito.tf#L114

I think this could be made configurable through a variable, for example:

`oauth_flows=[code, ...]`

There should probably also be a safeguard to prevent setting both `code` and `client_credentials`, as this is not allowed by AWS Cognito.

**Comment by kczpl** [comment]
Thanks for raising this issue! I have created a PR to solve it.
